### ISSUE TITLE
Dashboard improvements

### ISSUE THREAD

**Issue by talyguryn** [codex-team/hawk#113]
- [x] Вывести список существующих доменов
- [x] Если доменов нет, писать "добавьте проект"
- [ ] Под проектами идет список всех событий со всех проектов. В нем надо поправить ссылки, проверить корректность выставления доменов и открытия попапа.

**Comment by neSpecc** [comment]
- [ ] Вывести список существующих доменов
- [ ] Если доменов нет, писать "добавьте проект"
- [ ] Под проектами идет список всех событий со всех проектов. В нем надо поправить ссылки, проверить корректность выставления доменов и открытия попапа.
