### ISSUE TITLE
Is this project still active or dead?

### ISSUE THREAD

**Issue by yaneony** [codex-team/hawk#275]
There are no commits or releases and almost all stuff is outdated. Is it still maintained?

**Comment by nikmel2803** [comment]
Hi!
We are preparing for the release of the new major version (Hawk 2.0).
This is the repo for the first version, which is not currently maintained.
You can view source code of the new Hawk version in other repos:
- https://github.com/codex-team/hawk.garage
- https://github.com/codex-team/hawk.api.nodejs
- https://github.com/codex-team/workers
- and so on

Thank you for your interest.

**Comment by yaneony** [comment]
Ok, thanks for letting know. It would be nice to have some mention about V2 in this repository, so that everyone will know :D
