### ISSUE TITLE
Разработать общий шаблон писем

### ISSUE THREAD

**Issue by neSpecc** [codex-team/hawk#60]
- [x] Письмо с паролем
- [x] Уведомление об ошибке

**Comment by talyguryn** [comment]
Уведомление об ошибке

![image_2017-06-23_18-58-05](https://user-images.githubusercontent.com/15259299/27503334-db7e135a-5883-11e7-84dd-072a9c9648bf.png)

**Comment by talyguryn** [comment]
Есть макет письма с паролем?
